# Generated by Django 3.1 on 2020-08-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tb_users',
        ),
    ]
